CC = g++
CFLAGS = -g -std=c++11
LDFLAGS =
SOURCES = main.cpp 
INCLUDES =
OBJECTS = $(SOURCES:.cpp=.o)
LIBS =
EXECUTABLE = HMK6
$(EXECUTABLE):
	cd src; $(CC) $(CFLAGS) $(SOURCES) $(INCLUDES) -o ../$(EXECUTABLE).out

