CC = g++
CFLAGS = -std=c++11
LDFLAGS =
SOURCES = main.cpp
INCLUDES = 
OBJECTS = $(SOURCES:.cpp=.o)
LIBS =
EXECUTABLE = HMK5

$(EXECUTABLE):
	cd src; $(CC) $(CFLAGS) $(SOURCES) $(INCLUDES) -o ../$(EXECUTABLE).out


